Youtubeミニプレーヤー時のurl取得改善 #423
videomark/videomark pull request #223
Opened 2023-06-20 08:09 UTC by k1o0b1a9

下記のケースでMongoDBのsodium_collection内にあるlocationと実際に再生していた動画が紐づいていることを確認
- ミニプレーヤーで再生
- ミニプレーヤーで再生中、トラックアップで次の動画を再生
- ミニプレーヤーで再生中、ミニプレーヤーモードを解除して、トラックアップで次の動画を再生

2023-06-20 08:24 UTC, k1o0b1a9 commented
pnpm run lint:cspell　でfailになってしまいました、
これって具体的にどのファイルで引っかかったとかは出力されないのでしょうか。

2023-06-20 09:04 UTC, kou029w commented
eslint_report.json ですかね。ESLintによって自動生成されるファイルです。`pnpm lint` を実行して ESLint がパスすることをチェックしてみてください。

```
/home/runner/work/videomark/videomark/eslint_report.json:1:58563 - Unknown word (Cond)
/home/runner/work/videomark/videomark/eslint_report.json:1:58721 - Unknown word (Cond)
/home/runner/work/videomark/videomark/eslint_report.json:1:59297 - Unknown word (webm)
```

2023-06-21 01:40 UTC, acutus-fujii requested changes

2023-06-21 01:40 UTC, acutus-fujii commented on src/lib/content/sodium/modules/SessionData.js
> tver のフジTVコンテンツ用の実装で取得されたalt_locationを打ち消してしまう可能性があるのでそこだけ不安です

JavaScript コードはシングルスレッドで動作するので、227-229行目の if 文は必ずまとまって動作します。なので、
- alt_location に何か有効な値が入っていれば if 文は実行されない
- if 文が実行されたあとなら alt_location は自由に上書きされる

のどちらかで、いずれにしてもフジTVコンテンツ用コードには影響しないはずです。

2023-06-21 01:40 UTC, acutus-fujii commented on src/lib/content/sodium/modules/SessionData.js
storeSession で alt_location に undefined を代入するのは、どのような意図でしょうか。

2023-06-21 01:40 UTC, acutus-fujii commented on src/lib/content/sodium/modules/YouTubeTypeHandler.js
this.player は constructor が初期化しているはずなので、自分では代入せずに、そのまま使うことを検討してください。

https://music.youtube.com/ といったサイトがあるので、URL の取り扱いは難しいです。music.youtube.com にもミニプレーヤ機能があるので、試してみてください。

2023-06-21 01:55 UTC, k1o0b1a9 commented on src/lib/content/sodium/modules/SessionData.js
下記のようなケースで前の動画のURLを引き継いでしまうのでalt_location = undefined で一度リセットしています。
- ミニプレーヤーでの再生(alt_locationに値が入る)→トラックアップで次の動画を再生
-  ミニプレーヤーでの再生(alt_locationに値が入る)→ミニプレーヤー解除→次の動画を再生

また、リセット処理をstoreSessionに実装した意図としては
alt_locationがstoreSessionとtoJsonで参照されていて、
順番としてはstoreSessionの方が後なのでstoreSessionに実装しました。

2023-06-21 02:58 UTC, acutus-fujii commented on src/lib/content/sodium/modules/SessionData.js
状況や意図については理解しました。
しかし、storeSession が副作用として alt_location をリセットするのは、次の理由でよくないと思います。
- 関数名から副作用があることが読み取れない
- storeSession の後に処理が追加される可能性がある
- storeSession は setTimeout から起動される非同期処理で、実行順は決まっていない

storeSession の実行をスケジュールする関数 playing が、video の切り替わりを監視しています。そして、関数 start に、連続する video 再生を処理するループが記述されています。

関数 start のループで、this.location を初期化した直後に、this.alt_location をリセットするのが良いと思いました。

2023-06-21 04:14 UTC, k1o0b1a9 commented on src/lib/content/sodium/modules/SessionData.js
> 関数名から副作用があることが読み取れない
storeSession の後に処理が追加される可能性がある

確かに別の人がstoreSessionを手直しするってなると何かしら不具合の原因になりそうですね、、、

> storeSession は setTimeout から起動される非同期処理で、実行順は決まっていない

非同期処理ということは考慮できていませんでした

> 関数 start のループで、this.location を初期化した直後に、this.alt_location をリセットするのが良いと思いました

startのループで初期化するとinitのaltSessionMessageでalt_locationが書き換わっていた場合、
意図せず初期化してしまうことになるので別の箇所の方か初期化に条件を付ける必要がありそうです。

2023-06-21 04:46 UTC, acutus-fujii commented on src/lib/content/sodium/modules/SessionData.js
> startのループで初期化するとinitのaltSessionMessageでalt_locationが書き換わっていた場合

そうですね。同じ変数を使うのをやめたほうが簡単な気がしてきました。例えば、こんな感じ。

  this.alt_location || video.get_location()

2023-06-21 05:18 UTC, k1o0b1a9 commented on src/lib/content/sodium/modules/SessionData.js
> this.alt_location || video.get_location()

video.get_location()はget_alt_locationのことですか?

2023-06-21 05:45 UTC, acutus-fujii commented on src/lib/content/sodium/modules/SessionData.js
alt_location を取得するので get_alt_location という名前が良いと思ったのですが、location 取得に使うのなら get_location かなと。
次の方法も考えられるかも。

this.alt_location || video.get_alt_location() || this.location.href

2023-06-21 05:54 UTC, k1o0b1a9 commented on src/lib/content/sodium/modules/SessionData.js
変数として扱わずに返り値を直接送信箇所に使っちゃうってことですね!
確かにそれならget_locationの方が適当な感じがするのでそれで試してみます。

2023-06-21 08:41 UTC, k1o0b1a9 commented on src/lib/content/sodium/modules/YouTubeTypeHandler.js
constructorに対して代入せず直接使用するようにしました
https://github.com/videomark/videomark/pull/223/commits/9466809b24aeaf6fd946bd3a545e8eb6fb107d0e

2023-06-21 08:56 UTC, acutus-fujii approved these changes
問題が解決されていると思います。

2023-06-21 08:56 UTC, acutus-fujii commented on src/lib/content/sodium/modules/YouTubeTypeHandler.js
https://music.youtube.com/ も Youtube のオフィシャルなサイトで、www.youtube.com と同じようにミニプレーヤ機能があり、
やはり同じようにミニプレーヤにするとアドレスバーから watch?v=xxx が削除されます。
とはいっても、そもそも現在の YoutubeHandler は music.youtube.com に対応していないので、別の issue にする問題だろうと思います。

2023-06-21 08:56 UTC, acutus-fujii commented on src/lib/content/sodium/modules/YouTubeTypeHandler.js
この変更はこれで良いと思います。

2023-06-21 09:12 UTC, acutus-fujii commented
見落としていました。
こっちも変更してください。
https://github.com/videomark/videomark/blob/6bb10a5e21f0c0a126a6178abbecc5714c51412b/src/lib/content/sodium/modules/SessionData.js#L503

2023-06-22 00:16 UTC, k1o0b1a9 commented
すいません、僕も見落としていました。
https://github.com/videomark/videomark/pull/223/commits/e0c48500086b35ffc3be103c911c7a58aaf3edaa で変更済みです

2023-06-22 00:35 UTC, acutus-fujii commented
> https://github.com/videomark/videomark/commit/e0c48500086b35ffc3be103c911c7a58aaf3edaa で変更済みです

確認しました。問題ありません。

2023-06-22 00:40 UTC, merged